Help:
  description: >
    Type HELP, INFO, INVENTORY, or QUIT. Commands are not case-sensitive.
    
    LOOK will show the current room's description again, but you can
    also use it to look at items in your inventory or items in the room
    ('look at fajitas' or just 'look fajitas').
    
    GET or TAKE will get an item from the current room ('get fajitas').
    
    EXITS shows the obvious exits out of the current room.
    
    USE will use an item in your inventory ('use fajitas'). You might need
    to tell the game what to use the item on ('use fajitas on king of town').
    
    Sometimes you can TALK to characters or GIVE items to characters.
    
    If all else fails, be creative and use your imaginiation.

Welcome:
  description: >
    Welcome to the the game! You can type HELP, INFO, INVENTORY, or QUIT.
    Commands are not case-sensitive.

Name:
  description: What is your name?
  success: 'Hello, |name|'
  error: Please type your name.
    
Start:
  intro: You awake slowly...
  description: You can't see much here. It's pitch black.
  description_with_flashlight: >
    You are in a small bedroom. With your flashlight, you can discern
    a few furnishings: a chair and desk, a bed, a dresser,
    and a closed window.
  items:
    - flashlight
  exits:
    south: start_hallway
    trap_door: { two_way: false, room: basement_entrance }